# ORIGINAL PATH
PATH = '../resources/'

# ORIGINAL DATA FOLDER
ORIGINAL_DATA = '../resources/ViMs/original/'

# PROCESSED CSV FILE FOR TRAIN
IR_TRAIN = 'train_ds.csv'

# PROCESSED CSV FILE FOR TEST
IR_TEST = 'valid_ds.csv'

# STOPWORDS FILE LIST FOR VIETNAMESE
STOP_WORDS = 'stopwords.txt'